/**
 * TENSA — PyTorch backend.  Consumes only the IR.
 *
 * Parameters are emitted into an explicit ParameterDict keyed by the IR
 * parameter identity, so shared stages provably reference one tensor.
 */
import { DimExpr, asConst, asVar, atomDef, dConst, evalDim, show } from "./dims";
import { emaDecay, paramsOfRegion } from "./exec";
import { IRAttr, IRGraph, IRModule, IRNode, IRPlan, isDimExpr } from "./ir";
import { isTensor } from "./types";

/** `1 - 0.99` without the float dust */
function pyNum(x: number): string {
  return String(Number(x.toPrecision(12)));
}

/**
 * Render a symbolic dimension as a Python expression over a dims dictionary
 * (`ref("K")` -> `dims["K"]`).  Floor divisions become `//`.  Previously a
 * non-constant extent was emitted as `dims["4*K"]`, a key that never exists
 * (H-003).
 */
function pyDim(d: DimExpr, ref: (name: string) => string): string {
  const c = asConst(d);
  if (c !== null) return String(c);
  const atom = (id: string): string => {
    const def = atomDef(id);
    if (def.kind === "var") return ref(def.name);
    return `(${pyDim(def.num, ref)} // ${pyDim(def.den, ref)})`;
  };
  const terms = [...d.terms.filter((t) => t.vars.length > 0), ...d.terms.filter((t) => t.vars.length === 0)];
  const parts = terms.map((t) => {
    const factors = t.vars.map(atom);
    if (!factors.length) return String(t.coef);
    if (t.coef === 1) return factors.join(" * ");
    if (t.coef === -1) return `-${factors.join(" * ")}`;
    return [String(t.coef), ...factors].join(" * ");
  });
  return d.terms.length > 1 ? `(${parts.join(" + ").replace(/\+ -/g, "- ")})` : parts[0];
}

/** attributes may be missing on programs that failed to check — never crash */
function dimAttr(a: IRAttr): DimExpr {
  return isDimExpr(a) ? a : dConst(1);
}
function dimList(a: IRAttr): DimExpr[] {
  return Array.isArray(a) && a.every(isDimExpr) ? (a as DimExpr[]) : [];
}

function py(name: string) {
  return name.replace(/[^A-Za-z0-9_]/g, "_");
}

export function emitTorch(mod: IRModule): string {
  const L: string[] = [];
  L.push("# Generated by the TENSA compiler — PyTorch backend");
  L.push("# The language semantics live in the IR; this file is one lowering of it.");
  L.push("import math");
  L.push("import torch");
  L.push("import torch.nn as nn");
  L.push("import torch.nn.functional as F");
  L.push("");
  L.push("def execution_device(requested=None):");
  L.push('    """GPU required by default; CPU is an explicit opt-in (H-011)."""');
  L.push('    if requested is None or str(requested) in ("auto", "gpu"):');
  L.push('        if torch.cuda.is_available(): return torch.device("cuda")');
  L.push('        if torch.backends.mps.is_available(): return torch.device("mps")');
  L.push('        raise RuntimeError("TENSA requires a GPU; explicitly select device=cpu to run on CPU")');
  L.push("    return torch.device(requested)");
  L.push("");
  L.push("def projected(cache, key, forward, index):");
  L.push('    """One tuple-valued forward per loss, not one per projection (F-023)."""');
  L.push("    if key not in cache: cache[key] = forward()");
  L.push("    return cache[key][index]");
  L.push("");
  L.push("def move_batch(batch, device):");
  L.push("    if isinstance(batch, torch.Tensor): return batch.to(device)");
  L.push("    if isinstance(batch, dict): return {k: move_batch(v, device) for k, v in batch.items()}");
  L.push("    if isinstance(batch, tuple): return tuple(move_batch(v, device) for v in batch)");
  L.push("    if isinstance(batch, list): return [move_batch(v, device) for v in batch]");
  L.push("    return batch");
  L.push("");
  L.push("def set_lr(opt, params, lr):");
  L.push('    """Region-level learning rate: move `params` into their own param group (H-006)."""');
  L.push("    ids = {id(p) for p in params}");
  L.push("    moved = []");
  L.push("    for g in opt.param_groups:");
  L.push('        moved += [p for p in g["params"] if id(p) in ids]');
  L.push('        g["params"] = [p for p in g["params"] if id(p) not in ids]');
  L.push('    opt.param_groups[:] = [g for g in opt.param_groups if g["params"]]');
  L.push("    if moved:");
  L.push('        opt.add_param_group({"params": moved, "lr": lr})');
  L.push("    for g in opt.param_groups:");
  L.push('        g["base_lr"] = g["lr"]');
  L.push("");
  L.push("def lr_multiplier(schedule, step, total):");
  L.push('    """Lifecycle schedule as a multiplier on each group\'s base_lr; mirrors the reference runtime (H-001)."""');
  L.push("    if not schedule:");
  L.push("        return 1.0");
  L.push('    kind, args = schedule["kind"], schedule["args"]');
  L.push('    warmup = args.get("warmup", 0)');
  L.push("    if warmup > 0 and step < warmup:");
  L.push("        return (step + 1) / warmup");
  L.push("    t = min(1.0, max(0.0, (step - warmup) / max(1, total - warmup)))");
  L.push('    if kind == "cosine":');
  L.push("        return 0.5 * (1 + math.cos(math.pi * t))");
  L.push('    if kind == "linear":');
  L.push("        return 1.0 - t");
  L.push('    if kind == "step":');
  L.push('        return args.get("gamma", 0.1) ** ((step - warmup) // max(1, int(args.get("every", 10))))');
  L.push("    return 1.0");
  L.push("");
  L.push("def apply_schedule(opts, schedule, step, total):");
  L.push("    m = lr_multiplier(schedule, step, total)");
  L.push("    for opt in opts:");
  L.push("        for g in opt.param_groups:");
  L.push('            g["lr"] = g.get("base_lr", g["lr"]) * m');
  L.push("");
  // constant dims are module-level; dims derived from runtime-bound ones
  // (`dim H = 4 * K`) are computed once the runtime bindings are known
  const env = new Map<string, number>();
  for (const d of mod.dims) {
    if (!d.value) continue;
    const v = evalDim(d.value, env);
    if (v !== null) env.set(d.name, v);
  }
  const staticDims = mod.dims.filter((d) => d.value !== null && env.has(d.name));
  const derivedDims = mod.dims.filter((d) => d.value !== null && !env.has(d.name));
  const runtimeDims = mod.dims.filter((d) => d.value === null);
  L.push("# --- symbolic dimensions -------------------------------------------------");
  L.push("STATIC_DIMS = {");
  for (const d of staticDims) L.push(`    "${d.name}": ${env.get(d.name)},`);
  L.push("}");
  if (runtimeDims.length)
    L.push(`# bound at runtime: ${runtimeDims.map((d) => d.name).join(", ")}`);
  L.push("");
  L.push("def resolve_dims(dims):");
  L.push('    """Runtime bindings plus the dims derived from them."""');
  L.push("    d = dict(STATIC_DIMS); d.update(dims)");
  for (const d of derivedDims)
    L.push(`    d["${d.name}"] = ${pyDim(d.value!, (n) => `d["${n}"]`)}  # ${d.name} = ${show(d.value!)}`);
  L.push("    return d");
  L.push("");

  for (const g of mod.graphs.filter((x) => x.kind === "model")) {
    L.push(...emitModule(mod, g, env));
    L.push("");
  }
  for (const o of mod.objectives) {
    L.push(`def objective_${py(o.name)}(${[...o.graph.inputs.map((i) => py(i.name ?? i.id)), "dims=None"].join(", ")}):`);
    L.push("    dims = resolve_dims(dims or {})");
    // ports are IR values like any other: alias them or the body raises NameError (H-006)
    for (const i of o.graph.inputs) L.push(`    v${i.id} = ${py(i.name ?? i.id)}`);
    L.push(`    device = ${o.graph.inputs.length ? `v${o.graph.inputs[0].id}.device` : "execution_device()"}`);
    const body = emitNodes(mod, o.graph.nodes, "    ", env, "dims");
    L.push(...body);
    L.push(`    return ${o.graph.outputs.map((x) => `v${x}`).join(", ")}`);
    L.push("");
  }
  for (const plan of mod.plans) L.push(...emitPlan(mod, plan));
  return L.join("\n");
}

function emitModule(mod: IRModule, g: IRGraph, env: Map<string, number>): string[] {
  const L: string[] = [];
  const params = mod.params.filter((p) => p.owner.split("/")[0] === g.name);
  const states = mod.states.filter((s) => s.owner.split("/")[0] === g.name);
  L.push(`class ${py(g.name)}(nn.Module):`);
  L.push("    def __init__(self, *, device=None, **dims):");
  L.push("        super().__init__()");
  L.push("        device = execution_device(device)");
  L.push('        self.register_buffer("_device_anchor", torch.empty(0, device=device), persistent=False)');
  L.push("        self.dims = dims = resolve_dims(dims)");
  L.push("        self.p = nn.ParameterDict()");
  for (const p of params) {
    const shape = p.shape.map((d) => evalDim(d, env) ?? pyDim(d, (n) => `dims["${n}"]`)).join(", ");
    const init =
      p.init === "zeros"
        ? `torch.zeros(${shape || "()"}, device=device)`
        : p.init === "ones"
        ? `torch.ones(${shape || "()"}, device=device)`
        : p.init === "kaiming"
        ? `nn.init.kaiming_normal_(torch.empty(${shape}, device=device))`
        : p.init === "normal"
        ? `torch.randn(${shape || "()"}, device=device) * 0.02`
        : `nn.init.xavier_uniform_(torch.empty(${shape}, device=device))`;
    L.push(
      `        self.p["${py(p.id)}"] = nn.Parameter(${init}, requires_grad=${p.trainable ? "True" : "False"})` +
        (p.applications.length > 1 ? `  # shared by ${p.applications.length} applications` : "")
    );
  }
  for (const s of states)
    L.push(
      `        self.register_buffer("${py(s.id)}", torch.${s.init === "ones" ? "ones" : "zeros"}(${s.shape
        .map((d) => evalDim(d, env) ?? pyDim(d, (n) => `dims["${n}"]`))
        .join(", ") || "()"}, device=device))  # persistent state, update=${s.update}`
    );
  L.push("");
  L.push(`    def forward(self, ${g.inputs.map((i) => py(i.name ?? i.id)).join(", ")}):`);
  for (const i of g.inputs) L.push(`        v${i.id} = ${py(i.name ?? i.id)}`);
  // runtime-bound dims (`dim B`, `dim T`) are read off the actual inputs, so
  // symbolic reshapes / slices / masks inside the body lower to real extents
  // instead of `-1` placeholders (H-005)
  const bound = new Map<string, string>();
  for (const i of g.inputs) {
    const t = mod.values.get(i.id)?.type;
    if (!t || !isTensor(t) || t.unknown) continue;
    t.shape.forEach((d, k) => {
      const v = asVar(d);
      if (v && !env.has(v) && !bound.has(v)) bound.set(v, `${py(i.name ?? i.id)}.shape[${k}]`);
    });
  }
  if (bound.size) {
    L.push(`        dims = resolve_dims({**self.dims, ${[...bound].map(([v, e]) => `"${v}": ${e}`).join(", ")}})`);
  } else L.push("        dims = self.dims");
  L.push("        device = self._device_anchor.device");
  L.push(...emitNodes(mod, g.nodes, "        ", env, "dims"));
  L.push(`        return ${g.outputs.map((o) => `v${o}`).join(", ")}`);
  return L;
}

function emitNodes(mod: IRModule, nodes: IRNode[], ind: string, env: Map<string, number>, dimsRef = "self.dims"): string[] {
  const L: string[] = [];
  for (const n of nodes) L.push(...emitNode(mod, n, ind, env, dimsRef));
  return L;
}

function emitNode(mod: IRModule, n: IRNode, ind: string, env: Map<string, number>, dimsRef: string): string[] {
  const L: string[] = [];
  const o = (i = 0) => `v${n.outputs[i]}`;
  const a = (i = 0) => `v${n.inputs[i]}`;
  const P = (i: number) => `self.p["${py(n.params[i] ?? "")}"]`;
  const ty = mod.values.get(n.outputs[0])?.type;
  const cmt = ty && isTensor(ty) ? `  # ${ty.kind}[${ty.shape.map(show).join(", ")}]` : "";
  const num = (k: string, d = 0) => Number(n.attrs[k] ?? d);
  // a symbolic extent inside a graph body: constant when provable, otherwise an
  // expression over the live dims dictionary (never `-1`, H-005)
  const dr = (d?: DimExpr) => (d ? (evalDim(d, env) ?? pyDim(d, (v) => `${dimsRef}["${v}"]`)).toString() : "0");
  switch (n.op) {
    case "const":
      return [`${ind}${o()} = torch.tensor(${num("value")}, device=device)`];
    case "const_dim":
      return [
        `${ind}${o()} = torch.tensor(float(${pyDim(dimAttr(n.attrs.dim), (v) => `${dimsRef}["${v}"]`)}), device=device)  # symbolic dim ${show(
          dimAttr(n.attrs.dim)
        )}`,
      ];
    case "param_read":
      return [`${ind}${o()} = self.p["${py(String(n.attrs.param))}"]`];
    case "state_read":
      return [`${ind}${o()} = self.${py(String(n.attrs.state))}`];
    case "state_update": {
      // `ema(r)`: r is the decay — the weight kept from the previous value — in
      // both backends (E-009)
      const rule = String(n.attrs.rule ?? "");
      const st = `self.${py(String(n.attrs.state))}`;
      const next = rule.startsWith("ema") ? `${pyNum(emaDecay(rule))} * ${st} + ${pyNum(1 - emaDecay(rule))} * ${a()}.detach()` : `${a()}.detach()`;
      return [`${ind}if self.training:  # persistent state update (${rule})`, `${ind}    ${st} = ${next}`, `${ind}${o()} = ${st}`];
    }
    case "linear":
      return [`${ind}${o()} = ${a()} @ ${P(0)}${n.params.length > 1 ? ` + ${P(1)}` : ""}${cmt}`];
    case "conv2d":
      return [
        `${ind}${o()} = F.conv2d(${a()}, ${P(0)}, ${n.params.length > 1 ? P(1) : "None"}, stride=${num("stride", 1)}, padding=${num("pad", 0)}, dilation=${num("dilation", 1)})${cmt}`,
      ];
    case "maxpool2d":
      return [`${ind}${o()} = F.max_pool2d(${a()}, ${num("kernel", 2)}, ${num("stride", 2)}, ${num("pad", 0)})${cmt}`];
    case "avgpool2d":
      return [`${ind}${o()} = F.avg_pool2d(${a()}, ${num("kernel", 2)}, ${num("stride", 2)})${cmt}`];
    case "upsample":
      return [`${ind}${o()} = F.interpolate(${a()}, scale_factor=${num("scale", 2)}, mode="nearest")${cmt}`];
    case "global_avgpool":
      return [`${ind}${o()} = ${a()}.mean(dim=(2, 3))${cmt}`];
    case "flatten":
      return [`${ind}${o()} = ${a()}.flatten(1)${cmt}`];
    case "embedding":
      return [`${ind}${o()} = F.embedding(${a()}.long(), ${P(0)})${cmt}`];
    case "positional":
      return [`${ind}${o()} = ${a()} + ${P(0)}[: ${a()}.shape[1]].unsqueeze(0)${cmt}`];
    case "layernorm":
      return [`${ind}${o()} = F.layer_norm(${a()}, (${a()}.shape[-1],), ${P(0)}, ${P(1)}, ${num("eps", 1e-5)})${cmt}`];
    case "rmsnorm":
      return [
        `${ind}${o()} = ${a()} * torch.rsqrt(${a()}.pow(2).mean(-1, keepdim=True) + ${num("eps", 1e-6)}) * ${P(0)}${cmt}`,
      ];
    case "batchnorm":
      return [
        `${ind}${o()} = F.batch_norm(${a()}, self.${py(n.states[0])}, self.${py(n.states[1])}, ${P(0)}, ${P(1)}, self.training, ${num("momentum", 0.1)}, 1e-5)${cmt}`,
      ];
    case "randn_like":
      return [`${ind}${o()} = torch.randn_like(${a()}, dtype=torch.float32)${cmt}`];
    case "dropout":
      return [`${ind}${o()} = F.dropout(${a()}, p=${num("p", 0.5)}, training=self.training)${cmt}`];
    case "attention": {
      const heads = dr(dimAttr(n.attrs.heads));
      const out = [
        `${ind}B, Tq, D = ${a()}.shape; H = ${heads}; DH = D // H`,
        `${ind}q = (${a()} @ ${P(0)}).view(B, Tq, H, DH).transpose(1, 2)`,
        `${ind}k = (${n.inputs[1] ? a(1) : a()} @ ${P(1)}).view(B, -1, H, DH).transpose(1, 2)`,
        `${ind}v = (${n.inputs[2] ? a(2) : n.inputs[1] ? a(1) : a()} @ ${P(2)}).view(B, -1, H, DH).transpose(1, 2)`,
      ];
      // the mask port: TENSA masks are true where attention is *blocked*; SDPA's
      // boolean attn_mask is true where attention is *allowed*.  Rank 2 [Tq, Tk]
      // and rank 3 [B|1, Tq|1, Tk] masks are broadcast over heads (F-012)
      if (n.inputs[3]) {
        const mt = mod.values.get(n.inputs[3])?.type;
        const rank = mt && isTensor(mt) ? mt.shape.length : 2;
        out.push(`${ind}m = ~${a(3)}.bool()${rank === 2 ? "[None, None]" : rank === 3 ? "[:, None]" : ""}`);
        if (n.attrs.causal)
          out.push(`${ind}m = m & torch.tril(torch.ones(Tq, k.shape[2], dtype=torch.bool, device=q.device))`);
        out.push(`${ind}att = F.scaled_dot_product_attention(q, k, v, attn_mask=m)`);
      } else out.push(`${ind}att = F.scaled_dot_product_attention(q, k, v, is_causal=${n.attrs.causal ? "True" : "False"})`);
      out.push(`${ind}${o()} = att.transpose(1, 2).reshape(B, Tq, D) @ ${P(3)}${cmt}`);
      return out;
    }
    case "softmax":
      return [`${ind}${o()} = F.softmax(${a()}, dim=${num("axis", -1)})${cmt}`];
    case "log_softmax":
      return [`${ind}${o()} = F.log_softmax(${a()}, dim=${num("axis", -1)})${cmt}`];
    case "matmul":
      return [`${ind}${o()} = ${a()} @ ${a(1)}${cmt}`];
    case "transpose":
      return [`${ind}${o()} = ${a()}.transpose(${num("i")}, ${num("j")})${cmt}`];
    case "reshape":
      return [`${ind}${o()} = ${a()}.reshape(${dimList(n.attrs.shape).map((d) => dr(d)).join(", ")})${cmt}`];
    case "concat":
      return [`${ind}${o()} = torch.cat([${n.inputs.map((i) => `v${i}`).join(", ")}], dim=${num("axis", 1)})${cmt}`];
    case "stack":
      return [`${ind}${o()} = torch.stack([${n.inputs.map((i) => `v${i}`).join(", ")}], dim=${num("axis", 0)})${cmt}`];
    case "add":
    case "sub":
    case "mul":
    case "div": {
      const sym = { add: "+", sub: "-", mul: "*", div: "/" }[n.op];
      return [`${ind}${o()} = ${a()} ${sym} ${a(1)}${cmt}`];
    }
    case "merge_add":
    case "merge_mean": {
      // n-ary branch join (F-005): never the binary `+` or the `.mean()` reduction
      const sum = n.inputs.map((i) => `v${i}`).join(" + ");
      return [`${ind}${o()} = ${n.op === "merge_mean" ? `(${sum}) / ${n.inputs.length}` : sum}${cmt}`];
    }
    case "mean":
    case "sum":
    case "max":
    case "min":
    case "argmax": {
      const fn = n.op === "argmax" ? "argmax" : n.op;
      const ax = n.attrs.axis === null || n.attrs.axis === undefined ? "" : `dim=${num("axis")}, `;
      return [`${ind}${o()} = ${a()}.${fn}(${ax}${n.attrs.keep ? "keepdim=True" : ""})${cmt}`];
    }
    case "masked_fill":
      return [`${ind}${o()} = ${a()}.masked_fill(${a(1)}, ${num("value")})${cmt}`];
    case "causal_mask": {
      const nn = dr(dimAttr(n.attrs.n));
      return [`${ind}${o()} = torch.triu(torch.ones(${nn}, ${nn}, dtype=torch.bool, device=device), diagonal=1)${cmt}`];
    }
    case "one_hot":
      return [`${ind}${o()} = F.one_hot(${a()}.long(), ${dr(dimAttr(n.attrs.classes))}).float()${cmt}`];
    case "stop_grad":
      return [`${ind}${o()} = ${a()}.detach()  # gradient intentionally stopped`];
    case "detach_kind":
      return [`${ind}${o()} = ${a()}  # semantic kind reinterpreted (no runtime effect)`];
    case "slice": {
      if (n.attrs.dynamic) {
        const starts = dimList(n.attrs.from), ends = dimList(n.attrs.to);
        const openTo = n.attrs.openTo as number[];
        const parts = (n.attrs.kinds as string[]).map((kind, i) => kind === "ellipsis" ? "..." : kind === "all" ? ":" : kind === "index" ? dr(starts[i]) : `${dr(starts[i])}:${openTo[i] ? "" : dr(ends[i])}`);
        return [`${ind}${o()} = ${a()}[${parts.join(", ")}]  # F-030: runtime-ranked slice, static result unknown`];
      }
      const axes = (n.attrs.axes as number[]) ?? [];
      const from = dimList(n.attrs.from);
      const to = dimList(n.attrs.to);
      const drop = (n.attrs.drop as number[]) ?? [];
      if (!axes.length) return [`${ind}${o()} = ${a()}${cmt}`];
      const rank = Math.max(...axes) + 1;
      const parts: string[] = [];
      for (let i = 0; i < rank; i++) {
        const k = axes.indexOf(i);
        if (k < 0) parts.push(":");
        else if (drop[k]) parts.push(dr(from[k]));
        else parts.push(`${dr(from[k])}:${dr(to[k])}`);
      }
      return [`${ind}${o()} = ${a()}[${parts.join(", ")}]${cmt}`];
    }
    case "cross_entropy":
      return [`${ind}${o()} = F.cross_entropy(${a()}.reshape(-1, ${a()}.shape[-1]), ${a(1)}.reshape(-1).long())`];
    case "mse":
      return [`${ind}${o()} = F.mse_loss(${a()}, ${a(1)})`];
    case "bce":
      return [`${ind}${o()} = F.binary_cross_entropy(${a()}, ${a(1)})`];
    case "cosine_similarity":
      return [`${ind}${o()} = F.cosine_similarity(${a()}, ${a(1)}, dim=${num("axis", -1)})${cmt}`];
    case "l2":
      return [`${ind}${o()} = ${a()}.pow(2).sum()`];
    case "relu":
    case "gelu":
    case "silu":
    case "sigmoid":
    case "tanh":
      return [`${ind}${o()} = F.${n.op === "tanh" ? "tanh" : n.op}(${a()})${cmt}`];
    case "exp":
    case "log":
    case "sqrt":
    case "rsqrt":
    case "abs":
      return [`${ind}${o()} = torch.${n.op}(${a()})${cmt}`];
    case "neg":
      return [`${ind}${o()} = -${a()}${cmt}`];
    case "residual": {
      L.push(`${ind}# residual topology`);
      L.push(...emitNodes(mod, n.regions![0].nodes, ind, env, dimsRef));
      L.push(`${ind}${o()} = v${n.regions![0].results[0]}`);
      if (n.regions![1]) {
        L.push(`${ind}# explicit projection on the skip path`);
        L.push(...emitNodes(mod, n.regions![1].nodes, ind, env, dimsRef));
        L.push(`${ind}${o(1)} = v${n.regions![1].results[0]}`);
      }
      return L;
    }
    case "parallel": {
      L.push(`${ind}# parallel split: every branch consumes ${a()}`);
      n.regions!.forEach((r, i) => {
        L.push(`${ind}# branch ${r.label}`);
        L.push(...emitNodes(mod, r.nodes, ind, env, dimsRef));
        L.push(`${ind}${o(i)} = v${r.results[0]}`);
      });
      return L;
    }
    case "static_repeat": {
      L.push(`${ind}# static repetition x${num("count")} (${n.attrs.mode})`);
      n.regions!.forEach((r) => {
        L.push(`${ind}# ${r.label}`);
        L.push(...emitNodes(mod, r.nodes, ind, env, dimsRef));
      });
      const lastR = n.regions![n.regions!.length - 1];
      if (n.outputs.length && lastR?.results[0]) L.push(`${ind}${o()} = v${lastR.results[0]}`);
      else if (n.outputs.length && n.inputs.length) L.push(`${ind}${o()} = ${a()}  # zero repetitions: identity`);
      return L;
    }
    case "apply": {
      L.push(`${ind}# apply ${n.attrs.stage}${n.sharedStage ? " (shared parameters)" : ""}`);
      const r = n.regions![0];
      L.push(...emitNodes(mod, r.nodes, ind, env, dimsRef));
      r.results.forEach((res, i) => L.push(`${ind}${o(i)} = v${res}`));
      return L;
    }
    case "scan": {
      const r = n.regions![0];
      L.push(`${ind}# runtime recurrence (scan over axis ${num("axis", 1)})`);
      L.push(`${ind}_outs = []`);
      ((n.attrs.carry_values as string[]) ?? []).forEach((cid, i) => {
        const t = mod.values.get(cid)?.type;
        L.push(
          `${ind}v${cid} = torch.${((n.attrs.init as string[]) ?? [])[i] === "ones" ? "ones" : "zeros"}(${
            t && isTensor(t) ? `(${t.shape.map((d) => dr(d)).join(", ")},)` : "()"
          }, device=${a()}.device)`
        );
      });
      L.push(`${ind}for _t in range(${a()}.shape[${num("axis", 1)}]):`);
      L.push(`${ind}    v${String(n.attrs.step_value)} = ${a()}.select(${num("axis", 1)}, _t)`);
      L.push(...emitNodes(mod, r.nodes, ind + "    ", env, dimsRef));
      r.results.forEach((res, i) => {
        const cid = ((n.attrs.carry_values as string[]) ?? [])[i];
        if (cid) L.push(`${ind}    v${cid} = v${res}`);
      });
      L.push(`${ind}    _outs.append(v${r.results[0]})`);
      L.push(`${ind}${o()} = torch.stack(_outs, dim=${num("axis", 1)})`);
      ((n.attrs.carry_values as string[]) ?? []).forEach((cid, i) => {
        if (n.outputs[i + 1]) L.push(`${ind}${o(i + 1)} = v${cid}`);
      });
      return L;
    }
    default: {
      const custom = mod.customOps.find((c) => c.name === n.op);
      if (custom) {
        const impl = custom.backends.find((b) => b.target === "torch");
        return [
          `${ind}${o()} = ${impl ? impl.code : `NotImplemented  # no torch implementation declared for '${n.op}'`}${cmt}`,
        ];
      }
      return [`${ind}${o()} = NotImplemented  # backend gap: '${n.op}'`];
    }
  }
}

/** `a, f(b, c), d` split at top-level commas */
function splitArgs(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let cur = "";
  for (const ch of s) {
    if (ch === "(" || ch === "[") depth++;
    else if (ch === ")" || ch === "]") depth--;
    if (ch === "," && depth === 0) {
      out.push(cur.trim());
      cur = "";
    } else cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

/**
 * The training plan is lowered to one plain Python function.  Every
 * lifecycle mechanic the IR records is executable here — alias-correct
 * optimizer regions, persistent freeze/unfreeze, region learning rates,
 * schedules, `until`, `every … { validate ; checkpoint }`, `clip_grad`,
 * tracked EMA shadows and nested model bindings such as `D(G(z))` (H-001,
 * H-006, H-007).
 */
function emitPlan(mod: IRModule, plan: IRPlan): string[] {
  const L: string[] = [];
  const aliasOfModel = (model: string) => plan.models.find((m) => m.model === model)?.alias ?? model;
  /** parameter ids of a region together with the Python variable that owns them */
  const region = (r: string) => {
    const ps = paramsOfRegion(mod, plan, r);
    const owner = aliasOfModel(ps[0]?.owner.split("/")[0] ?? r.split(".")[0]);
    return { owner: py(owner), ids: ps.map((p) => p.id) };
  };
  /** Python list of the parameter tensors named by `ids`, grouped by the model alias that owns each (a `*` region spans several) */
  const paramList = (ids: string[]) => {
    const groups = new Map<string, string[]>();
    for (const id of ids) {
      const owner = py(aliasOfModel(mod.params.find((p) => p.id === id)?.owner.split("/")[0] ?? "model"));
      groups.set(owner, [...(groups.get(owner) ?? []), id]);
    }
    return [...groups].map(([owner, ps]) => `[${owner}.p[k] for k in [${ps.map((p) => `"${py(p)}"`).join(", ")}]]`).join(" + ") || "[]";
  };
  /** `D(G(z))[1]` → `D(G(batch["z"]))[1]` */
  const lowerBinding = (text: string): string => {
    const src = text.trim();
    const call = /^(\w+)\((.*)\)(\[\d+\])?$/.exec(src);
    if (call && plan.models.some((m) => m.alias === call[1])) {
      const forward = `${py(call[1])}(${splitArgs(call[2]).map(lowerBinding).join(", ")})`;
      return call[3] ? `projected(cache, ${JSON.stringify(`${call[1]}(${call[2]})`)}, lambda: ${forward}, ${call[3].slice(1, -1)})` : forward;
    }
    return `batch[${JSON.stringify(src)}]`;
  };
  const lossExpr = (l: IRPlan["losses"][number]) =>
    `objective_${py(l.objective)}(${l.bindings.map((b) => lowerBinding(b.text)).join(", ")}, dims=dims) * ${l.weight}`;
  const schedulePy = (s: string | null) => {
    if (!s) return "None";
    const kind = /^(\w+)/.exec(s)?.[1] ?? "constant";
    const args: string[] = [];
    for (const m of s.matchAll(/(\w+)\s*:\s*([\d.eE+-]+)/g)) args.push(`"${m[1]}": ${m[2]}`);
    return `{"kind": "${kind}", "args": {${args.join(", ")}}}`;
  };
  const clip = plan.settings.clip_grad ? parseFloat(plan.settings.clip_grad) : 0;
  const optOf = (name: string) => plan.optimizers.find((o) => o.name === name);

  L.push("# --- training plan -------------------------------------------------------");
  L.push(`def train_${py(plan.name)}(loader, val_loader=None, *, device=None, **dims):`);
  L.push(`    device = execution_device(device if device is not None else ${JSON.stringify(plan.settings.device ?? "auto")})`);
  const seen = new Map<string, string>();
  for (const m of plan.models) {
    const first = seen.get(m.model);
    if (first) L.push(`    ${py(m.alias)} = ${first}  # one model declaration is one parameter set: both aliases share it (AXS0706, F-015)`);
    else {
      L.push(`    ${py(m.alias)} = ${py(m.model)}(device=device, **dims)`);
      seen.set(m.model, py(m.alias));
    }
  }
  const first = plan.models[0] ? py(plan.models[0].alias) : null;
  L.push(`    dims = ${first ? `${first}.dims` : "resolve_dims(dims)"}`);
  L.push(`    models = {${plan.models.map((m) => `"${m.alias}": ${py(m.alias)}`).join(", ")}}`);
  for (const [k, v] of Object.entries(plan.settings)) if (k !== "clip_grad") L.push(`    # ${k} ${v}`);
  L.push("");
  L.push("    # optimizers — parameter regions resolved from IR owner paths, per alias");
  for (const o of plan.optimizers) {
    L.push(`    ${py(o.name)}_params = ${paramList(o.params)}  # over ${o.region}`);
    L.push(
      `    ${py(o.name)} = torch.optim.${o.kind === "sgd" ? "SGD" : o.kind === "adam" ? "Adam" : "AdamW"}(${py(o.name)}_params, lr=${o.lr}${
        o.args.wd ? `, weight_decay=${o.args.wd}` : ""
      }${o.kind === "sgd" && o.args.momentum ? `, momentum=${o.args.momentum}` : ""})`
    );
    L.push(`    for _g in ${py(o.name)}.param_groups: _g["base_lr"] = _g["lr"]`);
  }
  L.push("");
  L.push("    # losses — one closure per `loss`, reused by training and validation");
  for (const l of plan.losses) {
    L.push(`    def loss_${py(l.name)}(batch):`);
    L.push("        cache = {}  # fresh for each loss/update/validation");
    L.push(`        return ${lossExpr(l)}`);
  }
  L.push(`    losses = {${plan.losses.map((l) => `"${l.name}": loss_${py(l.name)}`).join(", ")}}`);
  if (plan.tracks.length) {
    L.push("");
    L.push("    # tracked shadows (`track t = ema(region, rate: r)`): a copy that follows the parameters");
    for (const t of plan.tracks) {
      const r = region(t.region);
      L.push(
        `    ${py(t.name)} = {k: ${r.owner}.p[k].detach().clone() for k in [${r.ids.map((p) => `"${py(p)}"`).join(", ")}]}  # ${t.kind}(${t.args})`
      );
    }
  }
  L.push("");
  L.push("    step = 0");
  L.push("    metrics = {}");
  L.push("");
  L.push("    def validate():");
  L.push("        out, n = {}, 0");
  L.push("        for m in models.values(): m.eval()");
  L.push("        with torch.no_grad():");
  L.push("            for batch in (val_loader or loader):");
  L.push("                batch = move_batch(batch, device)");
  L.push("                for name, fn in losses.items(): out[name] = out.get(name, 0.0) + float(fn(batch))");
  L.push("                n += 1");
  L.push("        for m in models.values(): m.train()");
  L.push('        return {"val_" + k: v / max(n, 1) for k, v in out.items()}');
  L.push("");
  L.push("    def checkpoint():");
  L.push("        torch.save({");
  L.push('            "step": step,');
  L.push('            "models": {k: m.state_dict() for k, m in models.items()},');
  L.push(`            "optimizers": {${plan.optimizers.map((o) => `"${o.name}": ${py(o.name)}.state_dict()`).join(", ")}},`);
  L.push(`            "tracks": {${plan.tracks.map((t) => `"${t.name}": ${py(t.name)}`).join(", ")}},`);
  L.push(`        }, f"${py(plan.name)}_step{step}.pt")`);
  L.push("");
  // one epoch of the reference runtime is STEPS_PER_EPOCH synthetic steps; the
  // emitted loop has a real loader, so epochs are loader passes
  const emitEvents = (events: IRPlan["events"], ind: string, unit: "steps" | "epochs", counter: string) => {
    for (const ev of events) {
      if (ev.unit !== unit) continue;
      L.push(`${ind}if ${counter} % ${ev.every} == 0:`);
      for (const a of ev.actions) {
        if (a.kind === "validate") L.push(`${ind}    metrics.update(validate())`);
        else if (a.kind === "checkpoint") L.push(`${ind}    checkpoint()`);
        else L.push(`${ind}    pass  # ${a.kind}(${a.args})`);
      }
    }
  };
  for (const ph of plan.phases) {
    const phaseOpts = [...new Set(ph.updates.flatMap((u) => u.optimizers))];
    L.push(`    # ---- phase ${ph.name}`);
    for (const r of ph.frozen) {
      const reg = region(r);
      L.push(`    for p in ${paramList(reg.ids)}: p.requires_grad_(False)  # freeze ${r}`);
    }
    for (const r of ph.unfrozen) {
      const reg = region(r);
      L.push(`    for p in ${paramList(reg.ids)}: p.requires_grad_(True)  # unfreeze ${r}`);
    }
    for (const lo of ph.lrOverrides) {
      const reg = region(lo.region);
      // the override applies to whichever optimizer of this phase claims those parameters
      const owners = phaseOpts.filter((n) => optOf(n)?.params.some((p) => reg.ids.includes(p)));
      for (const n of owners) L.push(`    set_lr(${py(n)}, ${paramList(reg.ids)}, ${lo.lr})  # lr ${lo.region} = ${lo.lr}`);
      if (!owners.length) L.push(`    # lr ${lo.region} = ${lo.lr}: no optimizer in this phase claims that region`);
    }
    const budget = ph.steps !== null ? `${ph.steps}` : `${ph.epochs} * len(loader)`;
    L.push(`    schedule = ${schedulePy(ph.schedule)}`);
    L.push(`    phase_step, phase_budget, stop = 0, ${budget}, False`);
    L.push(`    for epoch in range(${ph.steps !== null ? 1 : ph.epochs}):`);
    L.push(`        for batch in loader:`);
    L.push("            batch = move_batch(batch, device)");
    L.push(`            apply_schedule([${phaseOpts.map(py).join(", ")}], schedule, phase_step, phase_budget)`);
    for (const u of ph.updates) {
      const loss = plan.losses.find((l) => l.name === u.loss);
      if (!loss) continue;
      L.push(`            for _ in range(${u.times}):`);
      L.push(`                ${u.optimizers.map((x) => `${py(x)}.zero_grad(set_to_none=True)`).join("; ")}`);
      L.push(`                loss = loss_${py(loss.name)}(batch)`);
      L.push(`                loss.backward()`);
      if (clip > 0) for (const opt of u.optimizers) L.push(`                torch.nn.utils.clip_grad_norm_(${py(opt)}_params, ${clip})`);
      for (const opt of u.optimizers) L.push(`                ${py(opt)}.step()`);
      for (const t of plan.tracks) {
        if (t.kind !== "ema") continue;
        const decay = emaDecay(`ema(${t.args})`);
        const r = region(t.region);
        L.push(`                with torch.no_grad():  # track ${t.name}`);
        L.push(`                    for k, v in ${py(t.name)}.items(): v.mul_(${pyNum(decay)}).add_(${r.owner}.p[k].detach(), alpha=${pyNum(1 - decay)})`);
      }
      L.push(`            metrics["${loss.name}"] = metrics["train_${loss.name}"] = float(loss.detach())`);
    }
    L.push(`            step += 1; phase_step += 1`);
    // phase events count steps within the phase, plan-level events steps across the run (H-008)
    emitEvents(ph.events, "            ", "steps", "phase_step");
    emitEvents(plan.events, "            ", "steps", "step");
    if (ph.until) {
      const { metric, cmp, value } = ph.until;
      const fallback = cmp.startsWith("<") ? 'float("inf")' : '-float("inf")';
      L.push(`            if metrics.get("${metric}", ${fallback}) ${cmp} ${value}:  # until ${metric} ${cmp} ${value}`);
      L.push(`                stop = True; break`);
    }
    if (ph.steps !== null) {
      L.push(`            if phase_step >= phase_budget:`);
      L.push(`                break`);
    }
    emitEvents([...ph.events, ...plan.events], "        ", "epochs", "(epoch + 1)");
    L.push(`        if stop:`);
    L.push(`            break`);
  }
  L.push(`    return models, metrics`);
  return L;
}
